# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RemittanceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RappleProgressHUD'
  pod 'AlamofireObjectMapper'
  pod 'BrightFutures'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'goSellSDK/ErrorReporting' 

  # Pods for RemittanceApp

  target 'RemittanceAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemittanceAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
